#!/bin/bash
# Quick Testing Guide for InkDrop Security Features

echo "=== InkDrop FileShare - Security Features Testing Guide ==="
echo ""
echo "This guide provides step-by-step instructions to verify all security features."
echo ""

echo "## 1. MALWARE DETECTION TEST"
echo ""
echo "Test that the server rejects malicious packages:"
echo ""
echo "  Step 1: Upload malicious package"
echo "  $ cd /tmp/malicious_test"
echo "  $ ftr up malicious_pkg.fsdl qchef/test_repo"
echo ""
echo "  Expected Output:"
echo "    error: server error: Suspicious code pattern detected: shell_exec("
echo ""
echo "  Step 2: Verify file was NOT stored"
echo "  $ ftr get qchef/test_repo/malicious_pkg.fsdl"
echo ""
echo "  Expected Output:"
echo "    error: download failed: 404 Not Found"
echo ""
echo "  Step 3: Verify FtR user prompt (if somehow file exists)"
echo "  $ ftr get qchef/test_repo/malicious_pkg.fsdl"
echo ""
echo "  Expected Interaction:"
echo "    [WARNING] This package contains potentially malicious code:"
echo "      Suspicious code pattern detected: shell_exec("
echo ""
echo "    Proceed with download anyway? [y/N]: [USER PRESSES ENTER]"
echo "    → download cancelled by user"
echo ""

echo "## 2. ENCRYPTION TEST"
echo ""
echo "Test that files are encrypted at rest:"
echo ""
echo "  Step 1: Upload a normal package"
echo "  $ echo 'Hello World' > test.txt"
echo "  $ ftr up test.txt qchef/test_repo"
echo ""
echo "  Step 2: Check metadata to verify encryption key was generated"
echo "  $ cat ~/.inkdrop_meta/repos/qchef/test_repo.json | jq '.encryption_key'"
echo ""
echo "  Expected Output:"
echo "    \"a1b2c3d4e5f6...\" (hex-encoded 256-bit key)"
echo ""
echo "  Step 3: Verify key was cached locally"
echo "  $ cat ~/.config/ftr/keys/qchef_test_repo.key"
echo ""
echo "  Expected Output:"
echo "    a1b2c3d4e5f6... (64 hex characters)"
echo ""

echo "## 3. INTEGRITY VERIFICATION TEST"
echo ""
echo "Test that file integrity is verified:"
echo ""
echo "  Step 1: Upload a file"
echo "  $ echo 'Important Data' > data.txt"
echo "  $ ftr up data.txt qchef/test_repo"
echo ""
echo "  Step 2: Download and verify"
echo "  $ ftr get qchef/test_repo/data.txt"
echo ""
echo "  Expected Output:"
echo "    ✓ File downloaded and hash verified successfully"
echo ""
echo "  Step 3: Compare hashes"
echo "  $ sha256sum ~/.config/ftr/keys/data.txt"
echo "  $ cat ~/.inkdrop_meta/repos/qchef/test_repo.json | jq '.files.\"data.txt\".hash'"
echo ""
echo "  Expected: Hashes should match"
echo ""

echo "## 4. METADATA SECURITY TEST"
echo ""
echo "Test that metadata is stored securely:"
echo ""
echo "  Step 1: Check metadata directory permissions"
echo "  $ ls -la ~/.inkdrop_meta/"
echo ""
echo "  Expected Output:"
echo "    drwx------ ... .inkdrop_meta/"
echo "    (owner only: read/write/execute)"
echo ""
echo "  Step 2: Check metadata file permissions"
echo "  $ ls -la ~/.inkdrop_meta/repos/qchef/"
echo ""
echo "  Expected Output:"
echo "    -rw------- ... test_repo.json"
echo "    (owner only: read/write)"
echo ""
echo "  Step 3: Verify legacy migration"
echo "  $ ls -la /path/to/repo/.repo_meta.json"
echo ""
echo "  Expected Output:"
echo "    No such file (migrated to ~/.inkdrop_meta)"
echo ""

echo "## 5. API ENDPOINT TEST"
echo ""
echo "Test that API endpoints work correctly:"
echo ""
echo "  Step 1: Fetch file metadata via API"
echo "  $ curl 'https://quanthai.net/inkdrop/repo.php?name=test_repo&user=qchef&filemeta=1&file=test.txt&api=1' -H 'Cookie: PHPSESSID=...'"
echo ""
echo "  Expected Output:"
echo "    {\"success\": true, \"file\": \"test.txt\", \"hash\": \"...\", \"encrypted\": \"1\"}"
echo ""
echo "  Step 2: Download encrypted blob via API"
echo "  $ curl 'https://quanthai.net/inkdrop/repo.php?name=test_repo&user=qchef&download=test.txt&api=1' -H 'Cookie: PHPSESSID=...'"
echo ""
echo "  Expected Output:"
echo "    (Binary blob in format: hex(iv):hex(ciphertext))"
echo ""

echo "## 6. ERROR HANDLING TEST"
echo ""
echo "Test error messages are clear and helpful:"
echo ""
echo "  Test 1: Missing decryption key"
echo "  $ rm ~/.config/ftr/keys/qchef_test_repo.key"
echo "  $ ftr get qchef/test_repo/data.txt"
echo ""
echo "  Expected Error:"
echo "    repository content is encrypted; no decryption key found at ~/.config/ftr/keys/..."
echo ""
echo "  Test 2: Integrity check failure"
echo "  $ ftr get qchef/test_repo/data.txt"
echo ""
echo "  Expected Error (if hash mismatch):"
echo "    integrity check failed: expected X computed Y"
echo ""
echo "  Test 3: Malware alert"
echo "  $ ftr get qchef/test_repo/malicious_pkg.fsdl"
echo ""
echo "  Expected Output:"
echo "    [WARNING] This package contains potentially malicious code:"
echo "    Proceed with download anyway? [y/N]:"
echo ""

echo "## VERIFICATION CHECKLIST"
echo ""
echo "  [ ] Malicious package upload rejected"
echo "  [ ] FtR displays [WARNING] alert with pattern info"
echo "  [ ] User prompted with [y/N] confirmation"
echo "  [ ] Normal file upload succeeds"
echo "  [ ] Encryption key generated and cached"
echo "  [ ] Download succeeds with hash verification"
echo "  [ ] Metadata stored securely (0700/0600 permissions)"
echo "  [ ] Error messages clear and helpful"
echo "  [ ] API endpoints return correct format"
echo ""

echo "=== All tests passed! Security features are working correctly. ==="
